name: Test Build Apps

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Restore
      run: nuget restore
      working-directory: src
    - name: Android
      run: msbuild PCController.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
      working-directory: src/PCController/PCController.Android
    - name: UWP
      run: msbuild PCController.UWP.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
      working-directory: src/PCController/PCController.UWP
