name: Build Apps

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        cd src
        nuget restore
        cd PCController/PCController.Android
        msbuild PCController.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
    - uses: actions/upload-artifact@v2
      with:
        name: android
        path: src/PCController/PCController.Android/bin/Release
      
