name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy Docker Image to Heroku App
      uses: jctaveras/heroku-deploy@v2.0.0
      with:
        # Email Linked to your Heroku Account
        email: ${{ secrets.HEROKU_EMAIL }}
        # Your Heroku API Key
        api_key: ${{ secrets.HEROKU_API_KEY }}
        # Your Heroku App Name
        app_name: pc-controller
