name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy Docker Image to Heroku App
      uses: jctaveras/heroku-deploy@v2.0.0
      with:
        # Email Linked to your Heroku Account
        email: martingrman@outlook.com
        # Your Heroku API Key
        api_key: fa5b5e05-ef21-49c5-8aed-4a7bc0775fa6
        # Your Heroku App Name
        app_name: pc-controller